AllCops:
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassVars:
  Enabled: false

Layout/LineLength:
  Max: 120
