name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

defaults:
  run:
    working-directory: hexlet_code

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.0'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install dependencies
      run: make install

    - name: Run Rubocop
      run: make lint
    
    - name: Run Tests
      run: make test